spring:
  datasource:
    url: jdbc:postgresql://${dpg-d7nbcjgk1i2s739ire20-a}:${5432}/${booking_system}?sslmode=require
    username: ${project_cc3r_user}
    password: ${3eSkpGmC2OpT0fZw8NPUV72mOpS7k8V9}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

app:
  seed:
    demo-data: true
